export const SET_IMMERSIVE_ENABLED = 'SET_IMMERSIVE_ENABLED';
export const SET_IMMERSIVE_TEMPLATE = 'SET_IMMERSIVE_TEMPLATE';
export const SET_IMMERSIVE_ASSIGNMENTS = 'SET_IMMERSIVE_ASSIGNMENTS';
export const SET_IMMERSIVE_FOLLOW_ACTIVE_SPEAKER = 'SET_IMMERSIVE_FOLLOW_ACTIVE_SPEAKER';
export const SET_IMMERSIVE_SLOT_COUNT = 'SET_IMMERSIVE_SLOT_COUNT';


