export const OPEN_SAVESPEECHTOTEXT = 'OPEN_SAVESPEECHTOTEXT';
export const CLOSE_SAVESPEECHTOTEXT = 'CLOSE_SAVESPEECHTOTEXT';
export const SETUP_SAVESPEECHTOTEXT = 'SETUP_SAVESPEECHTOTEXT';
export const SET_SAVESPEECHTOTEXT_OPEN = 'SET_SAVESPEECHTOTEXT_OPEN';

export const setSaveSpeechToTextOpen = (isOpen: boolean) => ({
    type: SET_SAVESPEECHTOTEXT_OPEN,
    isOpen
});